name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Switch to Xcode 15.2
      run: sudo xcode-select -s "/Applications/Xcode_15.2.app"
    - name: Build
      run: xcodebuild -scheme itunes_missing_artwork -destination "platform=macOS" -destination "platform=iOS Simulator,name=iPhone 14"

#    - name: Show Destinations
#      run: xcodebuild -scheme itunes_missing_artwork -showdestinations
#    - name: Build (swift package manager macos default)
#      run: swift build -v
