name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v5
    - name: Switch to Xcode 16.0
      run: sudo xcode-select -s "/Applications/Xcode_16.0.app"
    - name: Build
      run: xcodebuild -scheme itunes_missing_artwork -destination "generic/platform=macOS" -destination "generic/platform=iOS Simulator"

#    - name: Show Destinations
#      run: xcodebuild -scheme itunes_missing_artwork -showdestinations
#    - name: Build (swift package manager macos default)
#      run: swift build -v
