name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 14.3
      run: sudo xcode-select -s "/Applications/Xcode_14.3.app"
    - name: Build
      run: xcodebuild -scheme itunes_missing_artwork -destination "platform=macOS" -destination "platform=iOS Simulator,name=iPhone 14"
